parameters:
    uecode_qpush.request_listener.priority: 254
    uecode_qpush.request_listener.class: Uecode\Bundle\QPushBundle\EventListener\RequestListener
    uecode_qpush.registry.class: Uecode\Bundle\QPushBundle\Provider\ProviderRegistry
    uecode_qpush.provider.aws: Uecode\Bundle\QPushBundle\Provider\AwsProvider
